### ISSUE TITLE
.so problem: invalid ELF header

### ISSUE THREAD

**Issue by ShammyFu** [YapengTian/TDAN-VSR-CVPR-2020#43]
I run eval.py on Ubuntu 18.04 and the version of pytorch is 0.3.1.
The file make.sh has been executed already, but I got the following error information:

Traceback (most recent call last):
  File "eval.py", line 10, in <module>
    from model import ModelFactory
  File "/experiment/video_sr/TDAN-VSR-CVPR-2020/model.py", line 8, in <module>
    from modules import ConvOffset2d
  File "/experiment/video_sr/TDAN-VSR-CVPR-2020/modules/__init__.py", line 1, in <module>
    from .deform_conv import ConvOffset2d
  File "/experiment/video_sr/TDAN-VSR-CVPR-2020/modules/deform_conv.py", line 7, in <module>
    from functions import conv_offset2d
  File "/experiment/video_sr/TDAN-VSR-CVPR-2020/functions/__init__.py", line 1, in <module>
    from .deform_conv import conv_offset2d
  File "/experiment/video_sr/TDAN-VSR-CVPR-2020/functions/deform_conv.py", line 5, in <module>
    from _ext import deform_conv
  File "/experiment/video_sr/TDAN-VSR-CVPR-2020/_ext/deform_conv/__init__.py", line 3, in <module>
    from ._deform_conv import lib as _lib, ffi as _ffi
**ImportError: /experiment/video_sr/TDAN-VSR-CVPR-2020/_ext/deform_conv/_deform_conv.so: invalid ELF header**

Can you tell me how to solve this problem? Thanks in advance!

**Comment by YapengTian** [comment]
Could you print the PyTorch version to make sure you are using  0.3.1?

**Comment by YapengTian** [comment]
import torch
print(torch.__version__)

**Comment by ShammyFu** [comment]
> import torch
> print(torch.**version**)

Thank you for reply! I tried just now.
>>> import torch
>>> print(torch.__version__)
0.3.1
>>>

**Comment by ShammyFu** [comment]
> import torch
> print(torch.**version**)

The gcc version is 7.5.0. I don't know if it matters.

**Comment by YapengTian** [comment]
https://github.com/YapengTian/TDAN-VSR-CVPR-2020/issues/39#issuecomment-708288525

**Comment by YapengTian** [comment]
gcc 7.4.0 works.

**Comment by ShammyFu** [comment]
> gcc 7.4.0 works.

Hi, I downgraded gcc to 7.4.0 but still got the same error.
Do you have the _deform_conv.so file that can be successfully imported on the Linux platform?

**Comment by ShammyFu** [comment]
> gcc 7.4.0 works.

sorry, i discovered that I made an operational error. This problem has been solved. Thank you very much~ ^^
